### Create client
GET http://localhost:8801/create?name=Vitalii

### Generate client (via ApiGateway)
GET http://localhost:9090/client/create?name=Vitalii Ivanov

### Get client info
GET http://localhost:8801/get

### Get client info (via ApiGateway)
GET http://localhost:9090/client/get

### Update client name
GET http://localhost:8801/update/1?name=Vitalii Ivanov

### Update client name (via ApiGateway)
GET http://localhost:9090/client/update/2?name=Vitalii Ivanov

### Get info about client with id 1
GET http://localhost:8801/get/1

### Get info about client with id 1 (via ApiGateway)
GET http://localhost:9090/client/get/2

### Delete client with id 1
GET http://localhost:8801/delete/1

### Delete client with id 1 (via ApiGateway)
GET http://localhost:9090/client/delete/1





